spring.application.name=WordPreprocessor
app.input-dir=src/main/resources/data/input
app.output-dir=src/main/resources/data/output
tfidf.enabled=true
search.mode=vector
search.topn=10
# ???? ??????? (?? ????????? 8080)
server.port=8080